server:
  port: 8080

spring:
  data:
    mongodb:
    # uri: ${MONGODB_URI:mongodb://localhost:27017/shodhdb}
      uri: mongodb+srv://nipunjaipur:avzfc5ca@cluster0.brmeq86.mongodb.net/shodhdb

logging:
  level:
    root: INFO
    com.shodh: DEBUG
